#!/usr/bin/env bash
# bash script to display and extract for a subdomain and domain
# acquire record type and ip address of subdomains

check_ip () {
	if [ $# -gt 1 ] 
	then
		RE=$(dig $SUB.$DOMAIN | grep -A 1 "ANSWER SECTION"| awk '{print $4}')
		IP=$(dig $SUB.$DOMAIN | grep -A 1 "ANSWER SECTION" | awk '{print $5}') 
		echo The subdomain "$SUB" is a $RE record and points to $IP
	else
		for str in ${collection[@]}
	       	do
			RE=$(dig $str.$DOMAIN | grep -A 1 "ANSWER SECTION"| awk '{print $4}')
                	IP=$(dig $str.$DOMAIN | grep -A 1 "ANSWER SECTION" | awk '{print $5}')
                	echo The subdomain "$str" is a $RE record and points to $IP
		done
	fi
}

DOMAIN=$1
SUB=$2
collection=("www" "lb-01" "web-01" "web-02")

check_ip $1 $2
