#!/usr/bin/env bash
# bash script to display and extract for a subdomain and domain
# acquire record type and ip address of subdomains

info_domain () {
    TEMP=$(dig $2.$1 | awk '/ANSWER SECTION:/{getline;print;}')
    REC=$(echo $TEMP | cut -d' ' -f 4)
    IP=$(echo $TEMP | cut -d' ' -f 5)
    echo "Subdomain $2 is a $REC record and points to $IP"
}
if [ "$#" -lt 1 ]
then
    echo "Usage: 0-world_wide_web DOMAIN SUBDOMAIN(optional)"
elif [ "$#" -eq 1 ]
then
    info_domain "$1" "www"
    info_domain "$1" "lb-01"
    info_domain "$1" "web-01"
    info_domain "$1" "web-02"
else
    info_domain "$1" "$2"
fi
